### ISSUE TITLE
GraphQL client should not be initialized for every request

### ISSUE THREAD

**Issue by haomingyin** [Authing/authing-py-sdk#13]
https://github.com/Authing/authing-py-sdk/blob/4f0decef59defc18ebec9cdca8b9782ccbc07dfa/authing/v2/common/graphql.py#L41-L42

The `fetch_schema_from_transport` has been enabled by default and thus each client initialization would preflight with a redundant schema introspection request. The GraphQL client should be cached if a token has not expired for performance improvement.

**Comment by liaochangjiang** [comment]
Thanks for your nice suggestion, it seems  `fetch_schema_from_transport` is useful only when we need local validation, and our GraphQL `query` is auto generated by our automation tool, so we can guarantee that `query` is valid.

So we may remove this parameter is the future release.
